services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: team_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/team_lms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


      APP_S3_PRESIGN_PUT_EXPIRES_SECONDS: "300"
      APP_S3_PRESIGN_KEY_PREFIX: "lms/extra-session-videos"

      AWS_ACCESS_KEY_ID: ${MY_AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MY_AWS_SECRET_KEY}

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    depends_on:
      - db
